repos:

    - repo: local
      hooks:
        - id: poetry-install
          name: poetry install
          entry: poetry install
          language: python
          always_run: true
          pass_filenames: false
          stages: ["pre-push"]

        - id: prepare-pyproject-toml
          name: prepare pyproject.toml
          entry: bash scripts/prepare_pyproject.sh
          language: system
          always_run: true
          pass_filenames: false

        - id: generate-logs-coverage-badge
          name: generate logs coverage badge
          entry: bash scripts/generate_logs_coverage_badge.sh
          language: system
          always_run: true
          pass_filenames: false

        - id: generate-readme
          name: generate README
          entry: bash scripts/generate_readme.sh
          language: system
          always_run: true
          pass_filenames: false

