language: python

os:
  - linux

python:
  - "nightly"

# Adicionar bibliotecas do sistema antes de instalar as dependências do Python
addons:
  apt:
    packages:
      - libhunspell-dev
      - hunspell-en-us
      - hunspell-pt-br

install:
  - pip install -r requirements.txt

script:
  - pytest
