language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

# Adicionar bibliotecas do sistema antes de instalar as dependências do Python
addons:
  apt:
    packages:
      - libhunspell-dev
      - hunspell-en-us
      - hunspell-pt-br

install:
  - pip install -r requirements.txt

script:
  - pytest
