name: Build Windows
on: [push]

jobs:
  build:

    runs-on: windows-2022
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip upgrade
        run: |
          python -m pip install --upgrade pip

      #--- DISPLAY PYTHON VERSION
      - name: Display Python version
        run: 
          python -c "import sys; print(sys.version)"
      
      #--- SETUP YOUR ENVIRONMENT HERE
      ## INSTALL THE NECESSARY SOFTWARES FOR YOUR PROJECT
      - name: Install WKHtmlToPdf on Windows
        run: |
          choco install -y wkhtmltopdf  # Instala usando o Chocolatey (gerenciador de pacotes para Windows)
      
      #--- DEPENDENCIES
      ## INSTALL DEPENDENCIES PYTHON
      - name: Install config packages
        run: |
          pip install poetry

      - name: Install project dependencies
        run: |
          poetry install
        shell: pwsh

      #--- RUN    
      ## RUN YOUR SCRIPT HERE
      - name: Run code with Python
        run:
          scripts\run_main_pipeline.bat  # Executa um script no Windows

