name: Windows Run Unit Test via Pytest

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Especifica o Windows como o ambiente
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (
            pip install -r requirements.txt
          )

      - name: Install Enum34
        run: |
          pip install enum34

      - name: Install WKHtmlToPdf on Windows
        run: |
          choco install -y wkhtmltopdf  # Instala usando o Chocolatey (gerenciador de pacotes para Windows)

      - name: Install Hunspell
        run: |
          choco install -y hunspell.portable  # Instala a versão portátil do Hunspell via Chocolatey

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check . --target-version=py310
        continue-on-error: true

      - name: Install Coverage
        run: |
          pip install coverage

      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s

      - name: Generate Coverage Report
        run: |
          coverage report -m

      - name: Run main
        run: |
          scripts\run_main_pipeline.bat  # Executa um script no Windows
